
/*
* Each data class has copy, toString, equals and hashcode generated by
* default.*/
data class Person3(
    val name: String,
    val lastName: String?,
    val age: Int,
    val pet: Pet2
)

data class Pet2(val name: String, val animalType: String)

fun main() {
    val dog = Pet2("Max", "Germand Shepard Dog")
    val filip = Person3("Filip", "Babic", 23, dog)

    /*The data is formatted nicely, and you didn't even have to do any manual work.*/
    println(filip)

    val olderFilip = filip.copy(age = 20)
    println(olderFilip)

    /*
   * Challenge:
   *
   * Change the classes from the previous task to be `data` classes
   * instead, and remove unnecessary code, such as the formatting method, to rely on `toString()` instead.
   *
   * Also make sure the class is immutable (use `val`s instead of `var`s, public modifiers for access).
   * */

}